// Generated by CoffeeScript 1.6.3
(function() {
  var DialogViewModel, Extension, HighlineProvider, PhoenixT1DialogView, PhoenixT1Provider, Provider, View, _ref, _ref1, _ref2, _ref3,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;


  this.messages = {
    get: function(key) {
      var _ref;
      return (_ref = this['en'][key]) != null ? _ref : '#' + key + '#';
    }
  };

  /*
  Define the vars that will be used in the dialog
  */
  this.messages.en = {
    filter_dialog_title: 'Blocker',
    excluding: 'Excluding',
    including: 'Including',
    blocker: 'Blocker',
  };

  DialogViewModel = (function() {
    DialogViewModel.prototype.version = 2;

    DialogViewModel.prototype.settings = {
      termsList: '',
      termsExclude: true,
      usersList: '',
      usersExclude: true,
      enabled: true,
    };

    function DialogViewModel() {
      var $default, setting, _ref,
        _this = this;
      this.showWelcomeTip = ko.observable(true, {
        persist: 'TwitterFilter.showWelcomeTip_004'
      });
      _ref = this.settings;
      for (setting in _ref) {
        $default = _ref[setting];
        this[setting] = ko.observable($default, {
          persist: 'TwitterFilter.' + setting
        });
      }
      this.visible = ko.observable(false);
      this.termsExcludeText = ko.computed(function() {
        if (_this.termsExclude()) {
          return messages.get('excluding');
        } else {
          return messages.get('including');
        }
      });
      this.usersExcludeText = ko.computed(function() {
        if (_this.usersExclude()) {
          return messages.get('excluding');
        } else {
          return messages.get('including');
        }
      });
      this.bookmarklet = ko.computed(function() {
        var code, set, sets;
        set = function(setting) {
          var observable, value;
          observable = _this[setting];
          value = JSON.stringify(observable()).replace(/\\/g, "\\\\").replace(/\'/g, "\\'");
          return "s('" + observable.persistKey + "','" + value + "');";
        };
        sets = ((function() {
          var _results;
          _results = [];
          for (setting in this.settings) {
            _results.push(set(setting));
          }
          return _results;
        }).call(_this)).join('');
        code = "javascript:(function(){\nfunction s(k,v){window.localStorage.setItem(k,v);}\n" + sets + "\n$('<div id=\"blocker-reload\" data-version=\"" + _this.version + "\"></div>').appendTo($('#blocker-button'));\n})();";
        return code.replace(/\n/g, '');
      });
    }

    DialogViewModel.prototype.onSettingsChange = function(callback) {
      var setting, _results;
      _results = [];
      for (setting in this.settings) {
        _results.push(this[setting].subscribe(callback));
      }
      return _results;
    };

    DialogViewModel.prototype.toggle = function(attr) {
      return this[attr](!this[attr]());
    };

    DialogViewModel.prototype.toggleEnabled = function() {
      return this.toggle('enabled');
    };

    DialogViewModel.prototype.toggleVisible = function() {
      return this.toggle('visible');
    };

    DialogViewModel.prototype.toggleTermsExclude = function() {
      return this.toggle('termsExclude');
    };

    DialogViewModel.prototype.toggleUsersExclude = function() {
      return this.toggle('usersExclude');
    };

    return DialogViewModel;

  })();

  View = (function() {
    function View() {}

    View.prototype.render = function(viewModel) {
      throw new Error('Not implemented');
    };

    return View;

  })();

  PhoenixT1DialogView = (function(_super) {
    var _this = this;

    __extends(PhoenixT1DialogView, _super);

    function PhoenixT1DialogView() {
      _ref = PhoenixT1DialogView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PhoenixT1DialogView.prototype.render = function(viewModel) {
      this.renderButton(viewModel);
      this.renderDialog(viewModel);
      this.monitorBookmarklet(viewModel);
      return this.showWelcomeTip(viewModel);
    };

    PhoenixT1DialogView.prototype.renderButton = function(viewModel) {
      var buttonTemplate;
      buttonTemplate = function() {
        return li('#blocker-button', {
          'data-name': 'blocker'
        }, function() {
          return a('.js-blocker-dialog', {
            href: '#',
            'data-bind': 'click: toggleVisible'
          }, function() {
            return messages.get('blocker');
          });
        });
      };
      $('#user-dropdown ul li:nth-child(3)').after(CoffeeKup.render(buttonTemplate));
      return ko.applyBindings(viewModel, $('#blocker-button')[0]);
    };

    /*
    Create the dialog
    */

    PhoenixT1DialogView.prototype.renderDialog = function(viewModel) {
      var dialogHtml,
        _this = this;
      dialogHtml = CoffeeKup.render(this.dialogTemplate);
      return viewModel.visible.subscribe(function(visible) {
        return _this.visibleToggled(visible, dialogHtml, viewModel, {
          appendTo: 'body',
          center: true
        });
      });
    };

    PhoenixT1DialogView.prototype.dialogHeaderSelector = '.modal-header';


    /*
      function used to show the user interface for the extension
    */
    PhoenixT1DialogView.prototype.dialogTemplate = function() {
      return div('#blocker-dialog-container.modal-container.draggable', function() {
        div('.close-modal-background-target', function() {});
        return div('#blocker-dialog.modal', function() {
          return div('.modal-content', function() {
            button('.modal-btn.modal-close', {
              'data-bind': 'click: toggleVisible'
            }, function() {
              return span('.Icon.Icon--close.Icon--medium', function() {});
            });
            div('.modal-body', function() {
              return fieldset(function() {
                a('.btn.blocker-list-label', {
                  'data-bind': 'text: termsExcludeText, click: toggleTermsExclude'
                });
                input('.blocker-terms-list', {
                  'type': 'text',
                  'data-bind': "value: termsList, valueUpdate: ['change', 'afterkeydown']"
                });
                div(function() {
                  return '&nbsp;';
                });
                a('.btn.blocker-list-label', {
                  'data-bind': 'text: usersExcludeText, click: toggleUsersExclude'
                });
                input('.blocker-users-list', {
                  'type': 'text',
                  'data-bind': "value: usersList, valueUpdate: ['change', 'afterkeydown']"
                });
              });
            });
          });
        });
      });
    };

    PhoenixT1DialogView.prototype.visibleToggled = (function() {
      var container, overlay;
      container = null;
      overlay = $('<div class="twttr-dialog-overlay"></div>').appendTo($('body'));
      return function(visible, dialogHtml, viewModel, options) {
        var dialog;
        if (visible) {
          overlay.show();
          container = $(dialogHtml).appendTo($(options.appendTo));
          container.show();
          if (options.center) {
            dialog = $('#blocker-dialog');
            dialog.css('position', 'absolute').css('top', (($(window).height() - dialog.outerHeight()) / 2) + 'px').css('left', (($(window).width() - dialog.outerWidth()) / 2) + 'px');
          }
          container.draggable({
            handle: this.dialogHeaderSelector
          });
          container.on('keydown keypress', function(event) {
            return event.stopPropagation();
          });
          return ko.applyBindings(viewModel, container[0]);
        } else {
          container.find('.blocker-terms-list').tipsy('hide');
          container.find('.blocker-users-list').tipsy('hide');
          container.find('.blocker-bookmarklet').tipsy('hide');
          ko.cleanNode(container[0]);
          container.remove();
          return overlay.hide();
        }
      };
    })();

    PhoenixT1DialogView.prototype.monitorBookmarklet = function(viewModel) {
      return $('#blocker-button').on('DOMNodeInserted', function(event) {
        var el;
        el = $(event.target);
        viewModel.bookmarkletLoaded(el.data('version'));
        return el.remove();
      });
    };

    PhoenixT1DialogView.prototype.welcomeTip = function() {
      return $('#user-dropdown');
    };

    PhoenixT1DialogView.prototype.showWelcomeTip = function(viewModel) {
      var _this = this;
      if (viewModel.showWelcomeTip()) {
        return setTimeout(function() {
          _this.welcomeTip().tipsy({
            gravity: 'e',
            trigger: 'manual',
            html: true,
          }).tipsy('show').click(function() {
            return $(this).tipsy('hide');
          });
          setTimeout(function() {
            return _this.welcomeTip().tipsy('hide');
          }, 30000);
          return viewModel.showWelcomeTip(false);
        }, 3000);
      }
    };

    return PhoenixT1DialogView;

  }).call(this, View);

  Provider = (function() {
    function Provider() {}

    Provider.prototype.inMyProfilePage = function() {
      return this.screenUser() === this.sessionUser();
    };

    Provider.prototype.normalizeUser = function(x) {
      if (x != null) {
        return x.replace('@', '').trim();
      } else {
        return '';
      }
    };

    Provider.getActive = function() {
      var p, providers, _i, _len, _ref2;
      providers = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _ref2 = providers.map(function(x) {
        return new x;
      });
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        p = _ref2[_i];
        if (p.isActive()) {
          return p;
        }
      }
    };

    return Provider;

  })();

  PhoenixT1Provider = (function(_super) {
    __extends(PhoenixT1Provider, _super);

    function PhoenixT1Provider() {
      _ref2 = PhoenixT1Provider.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    PhoenixT1Provider.prototype.dialogView = new PhoenixT1DialogView;

    PhoenixT1Provider.prototype.isActive = function() {
      return $('body').hasClass('t1');
    };

    PhoenixT1Provider.prototype.filterCurrentPage = function() {
      var isIgnorablePage, _ref3;
      isIgnorablePage = (_ref3 = location.pathname + location.hash, __indexOf.call(this.ignorablePages(), _ref3) >= 0);
      return !(this.inMyProfilePage() || isIgnorablePage);
    };

    PhoenixT1Provider.prototype.ignorablePages = function() {
      return ['/' + this.sessionUser() + '/lists', '/i/#!/who_to_follow/suggestions', '/i/#!/who_to_follow/import', '/i/#!/who_to_follow/interests'];
    };

    PhoenixT1Provider.prototype.sessionUser = function() {
      return this.normalizeUser($('.account-group.js-mini-current-user').data('screen-name'));
    };

    PhoenixT1Provider.prototype.screenUser = function() {
      return this.normalizeUser($('.screen-name:not(.hidden)').text());
    };

    PhoenixT1Provider.prototype.tweets = function() {
      return $('div.tweet.js-stream-tweet');
    };

    PhoenixT1Provider.prototype.tweetText = function(el) {
      return $(el).find('.js-tweet-text, .tweet-text, .entry-content, .twtr-tweet-text').text();
    };

    PhoenixT1Provider.prototype.tweetAuthor = function(el) {
      return this.normalizeUser($(el).find('.username').text());
    };

    return PhoenixT1Provider;

  })(Provider);

  HighlineProvider = (function(_super) {
    __extends(HighlineProvider, _super);

    function HighlineProvider() {
      _ref3 = HighlineProvider.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    HighlineProvider.prototype.dialogView = new PhoenixT1DialogView;

    HighlineProvider.prototype.isActive = function() {
      return true;
    };

    HighlineProvider.prototype.filterCurrentPage = function() {
      var isIgnorablePage, _ref4;
      isIgnorablePage = (_ref4 = location.pathname + location.hash, __indexOf.call(this.ignorablePages(), _ref4) >= 0);
      return !(this.inMyProfilePage() || isIgnorablePage);
    };

    HighlineProvider.prototype.ignorablePages = function() {
      return ['/' + this.sessionUser() + '/lists', '/i/#!/who_to_follow/suggestions', '/i/#!/who_to_follow/import', '/i/#!/who_to_follow/interests'];
    };

    HighlineProvider.prototype.sessionUser = function() {
      return this.normalizeUser($('.account-group.js-mini-current-user').data('screen-name'));
    };

    HighlineProvider.prototype.screenUser = function() {
      return this.normalizeUser($('.ProfileHeaderCard-screenname').text());
    };

    HighlineProvider.prototype.tweets = function() {
      return $('div.tweet.js-stream-tweet, .Grid[data-component-term="tweet"]');
    };

    HighlineProvider.prototype.tweetText = function(el) {
      return $(el).find('.js-tweet-text, .entry-content, .ProfileTweet-text').text();
    };

    HighlineProvider.prototype.tweetAuthor = function(el) {
      return this.normalizeUser($(el).find('.username').text());
    };

    return HighlineProvider;

  })(Provider);

  /*
    extension function
  */
  Extension = (function() {
    Extension.prototype.provider = Provider.getActive(PhoenixT1Provider, HighlineProvider);

    function Extension() {
      var _this = this;
      this.dialogViewModel = new DialogViewModel;
      this.provider.dialogView.render(this.dialogViewModel);
      $(window).on('hashchange', function() {
        return setTimeout((function() {
          return _this.applyFilter();
        }), 500);
      });
      this.dialogViewModel.onSettingsChange(function() {
        return _this.applyFilter();
      });
      this.applyFilter();
    }

    Extension.prototype.applyFilter = function() {
      var _this = this;
      return this.throttle(10, function() {
        var apply, hiddenCount, hiddenUsers, termsRegExp, usersRegExp;
        apply = _this.dialogViewModel.enabled() && _this.provider.filterCurrentPage();
        if (apply) {
          termsRegExp = _this.filterRegExp(_this.filterPattern(_this.dialogViewModel.termsList(), false));
          usersRegExp = _this.filterRegExp(_this.filterPattern(_this.dialogViewModel.usersList(), true));
        }
        hiddenCount = 0;
        hiddenUsers = {};
        _this.provider.tweets().each(function(i, el) {
          var foundTermsMatches, foundUserMatches, termsMatch, tweetAuthor, usersMatch;
          termsMatch = false;
          usersMatch = false;
          if (apply) {
            tweetAuthor = _this.provider.tweetAuthor(el);
            if (termsRegExp != null) { //judge whether keyword matches
              termsRegExp.lastIndex = 0;
              foundTermsMatches = termsRegExp.test(_this.provider.tweetText(el));
              termsMatch = _this.dialogViewModel.termsExclude() === foundTermsMatches;
            }
            if (usersRegExp != null) {
              usersRegExp.lastIndex = 0;
              foundUserMatches = usersRegExp.test(tweetAuthor);
              usersMatch = _this.dialogViewModel.usersExclude() === foundUserMatches;
            }
          }
          if (termsMatch || usersMatch) {
            el.style.display = 'none';
            hiddenCount++;
          } else {
            return el.style.display = 'block';
          }
        });
        _this.reportViewModel.applied(apply).hasTerms(termsRegExp != null).hasUsers(usersRegExp != null).hiddenCount(hiddenCount).hiddenUsers(hiddenUsers);
        return _this.throttle(1000, function() {
          return _this.provider.reportView.render(_this.reportViewModel);
        });
      });
    };

    Extension.prototype.throttle = (function() {
      var timeout;
      timeout = {};
      return function(delay, fn) {
        var key;
        key = fn.toString();
        clearTimeout(timeout[key]);
        return timeout[key] = setTimeout(fn, delay);
      };
    })();

    Extension.prototype.filterPattern = function(csv, whole) {
      var values;
      values = csv.split(',');
      values = $.map(values, function(v, i) {
        v = $.trim(v);
        if (v.length > 2 && v[0] === '/' && v[v.length - 1] === '/') {
          return v.substr(1, v.length - 2);
        } else {
          return v.replace(/([\.\(\)\[\]\{\}\+\*\?\\])/g, '\\$1');
        }
      });
      values = $.grep(values, function(v, i) {
        return v !== '';
      });
      if (values.length === 0) {
        return null;
      }
      values = '(' + values.join('|') + ')';
      if (whole) {
        return "^" + values + "$";
      } else {
        return values;
      }
    };

    Extension.prototype.filterRegExp = function(pattern) {
      var e;
      if (pattern == null) {
        return null;
      }
      try {
        return new RegExp(pattern, 'gi');
      } catch (_error) {
        e = _error;
        return null;
      }
    };

    return Extension;

  })();

  new Extension();

}).call(this);
